version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./dockers/nginx/Dockerfile
    container_name: nginx
    restart: on-failure
    ports:
      - "9090:80"
    volumes:
      - type: volume
        source: web_data
        target: /web_data
      - type: bind
        source: ../../WebstormProjects/alone/dist
        target: /usr/share/nginx/html

  db:
    restart: always
    image: postgres:latest
    container_name: alone_db
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db_data
        target: /pg_data

  redis:
    image: redis:latest
    container_name: alone_redis
    ports:
      - "6379:6379"

  logspout:
    image: amouat/logspout-logstash
    container_name: alone_logspout
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
    ports:
      - "8000:80"
    depends_on:
      - logstash
    command: logstash://logstash:5959

  es:
    image: elasticsearch:latest
    container_name: alone_es
    restart: on-failure
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      LOGSPOUT: ignore
    volumes:
      - type: volume
        source: es_data
        target: /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"

  logstash:
    image: logstash:latest
    container_name: alone_logstash
    environment:
     LOGSPOUT: ignore
    command: logstash -f /etc/logstash.conf
    volumes:
      - type: volume
        source: logstash_data
        target: /usr/share/elasticsearch/data/

      - type: bind
        source: ./config/logstash.conf
        target: /etc/logstash.conf
    ports:
      - "5959:5959"
    depends_on:
      - es

  kibana:
    image: kibana:latest
    container_name: alone_kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es:9200
      LOGSPOUT: ignore
    depends_on:
      - es


  web: &django
    build:
      context: .
      dockerfile: ./dockers/alone/Dockerfile
    image: alone_web:wd
    command: sh ./dockers/alone/run.sh
    container_name: alone_web
    restart: always
#    deploy:
#      replicas:2
#      resources:
#        cpus: "0.1"
#        memory: 50M
#        restart_policy:
#          condition: on-failure
#    ports:
#      - "9000:9000"
    env_file:
      - ./env/web.env
    depends_on:
      - db
      - es
      - logstash
      - kibana
      - nginx
    logging:
      driver: "json-file"
    volumes:
      - type: volume
        source: web_data
        target: /web_data

  celerworker:
    <<: *django
    image: alone_celeryworker:wd
    container_name: alone_celeryworker
    depends_on:
      - redis
      - db
    ports: []
    command: sh ./dockers/celery/start_celeryworker.sh

  celerbeat:
    <<: *django
    image: alone_celerybeat:wd
    container_name: alone_celerybeat
    depends_on:
      - redis
      - db
    ports: []
    command: sh ./dockers/celery/start_celerybeat.sh


volumes:
  db_data:
  es_data:
  logstash_data:
  web_data: