version: '3.3'

services:
  db:
    restart: always
    image: postgres:latest
    container_name: alone_db
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: dbdata
        target: /pg_data

  web:
    build: .
    command: sh run.sh
    container_name: alone_web
#    deploy:
#      replicas:2
#      resources:
#        cpus: "0.1"
#        memory: 50M
#        restart_policy:
#          condition: on-failure
    ports:
      - "9000:9000"
    env_file:
      - ./env/web.env
    depends_on:
      - db

volumes:
  dbdata:
