# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='test', max_length=128),
        ),
    ]
